#!/bin/sh
# -*- coding: utf-8 -*-
NAME=`"checkurl"`
echo "Content-type:text/html\r\n"
echo "<html><head>"
echo "<title>$NAME</title>"
echo '<meta name="description" content="'$NAME'">'
echo '<meta name="keywords" content="'$NAME'">'
echo '<meta http-equiv="Content-type"
content="text/html;charset=UTF-8">'
echo '<meta name="ROBOTS" content="noindex">'
echo '<meta http-equiv="refresh" content="3;URL='/url'" />'
echo "</head><body><pre>"
/usr/bin/python /usr/local/webchecker/checkurl.py
echo "done......  and redirect to monitor page</pre></body></html>"
